### ISSUE TITLE
No text

### ISSUE THREAD

**Issue by arjepsen** [JamFfm/craftbeerpiLCD#3]
Hey.
I'm trying to get this to work, but I get no text on the display.
I'm using a raspberry pi zero W, with the rapsberry lite installation, and Craftbeerpi 3.0
I checked the display using the simple codes here:
http://www.circuitbasics.com/raspberry-pi-i2c-lcd-set-up-and-programming/
And with this I could get the display to show "hello world".
But no text with this plugin.
The address should be 0x27 - at least that's what I'm getting with 
sudo i2cdetect -y 1
The display is connected to 5V on pin 2
Tried reversing sda and scl connection, but then CBpi tells me that the lcd display isn't connected.
I assume the display is getting enough "juice", since I could get it to display "hello world" clearly with the simple code listed above.
Any help?

Regards
Anders

**Comment by JamFfm** [comment]
Thaks for using the addon,

first of all are you using stretch? I am afrait it will not work with stretch, just use jessie.

When CBPi3 mesh steps are active and you restart CBPi3 the display will show nothing. Stop and restart the Mesh steps.

If the address is right but you still can not see letters displayed: 
try to adjust contrast by the screw on the back of the LCD Hardware (I2C Modul)
be sure to provide the LCD hardware with the right ammount of voltage (mostly 5V or 3.3V)
use a strong powersuppy. If you notice LCD fading a bit there is a lack of current.
use proper connections. Soldering the wires is best for connection. Bad connection can also result in fading the LCD.

Other than that I never used or tested under pi Zero nore with raspian lite. 

In case there are some files missing durring installation of addon please deleate the folder LCDDisplay and install again.

In the logfile section there is a apps log. Please show the very beginning as there are some informations about the init phase of the LCDDisplay addon.

**Comment by JamFfm** [comment]
added hint to readme
