### ISSUE TITLE
Gravity on lcd

### ISSUE THREAD

**Issue by scolaone** [JamFfm/craftbeerpiLCD#4]
Hi,

Your plugin is good, but i'm using iSpindel and i'd like to get gravity on LCD (actual, OG and FG if possible)... Is it possible to add this option on your plugin ?

Thanks a lot !

**Comment by JamFfm** [comment]
Sure it is possible to extend the code. 
I will have a look if that makes sense and if I am able to realize that. 
It will take a longer time.

**Comment by avollkopf** [comment]
Hi,

I added this function to my fork. iSpindle snesor has to be defined as Gravity and used as sensor2 in a fermenter. Gravity is displayed in line 4 of the display. (I have tested my fork only under the python3 environment and it is running w/o problems) 
I have created a pull request

**Comment by JamFfm** [comment]
His function is added to the master. Thank you avollkopf for your input
